# Generated by Django 3.2.15 on 2022-10-12 19:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('has_taken_biometry_before', models.BooleanField(default=False, help_text='Tick if you have ever taken the biometry')),
                ('avatar', models.ImageField(default='', upload_to='uploads/')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=15)),
                ('username', models.EmailField(help_text='Type in your email, Required. Letters, numbers and @/./+/-/_ characters', max_length=254, null=True, unique=True)),
                ('phone', models.CharField(default='', max_length=14, null=True, unique=True)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('forget_password', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login', models.DateField(auto_now=True, null=True)),
                ('last_logout', models.DateField(auto_now=True, null=True)),
                ('country_of_orgin', models.CharField(default='', max_length=100)),
                ('country_of_destination', models.CharField(choices=[('Australia', 'Australia'), ('Canada', 'Canada'), ('USA', 'USA'), ('Shengen', 'Shengen'), ('Israel', 'Israel')], default='US', max_length=100)),
                ('nationality', models.CharField(default='', max_length=100)),
                ('next_of_kin', models.CharField(default='', help_text='whom would we call if you are not available', max_length=255)),
                ('next_of_kin_phone_number', models.CharField(default='', max_length=14)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountsExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_of', models.CharField(default='i.e: Transport of a good', max_length=250)),
                ('expense_by', models.CharField(default='i.e: Transport of a good', max_length=250)),
                ('amount', models.IntegerField(default='0')),
                ('day_on_which', models.DateField(blank=True, null=True)),
                ('evidence_document', models.ImageField(blank=True, default='', upload_to='uploads/')),
                ('signature', models.ImageField(blank=True, default='', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_of', models.CharField(default='Someone paid', max_length=250)),
                ('cashmemo_by', models.CharField(default='i.e: Transport of a good', max_length=250)),
                ('amount', models.IntegerField(default='0')),
                ('day_on_which', models.DateField(blank=True, null=True)),
                ('evidence_document', models.ImageField(blank=True, default='', upload_to='uploads/')),
                ('signature', models.ImageField(blank=True, default='', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='', upload_to='uploads/')),
                ('has_passport', models.BooleanField(default=True)),
                ('passport_document', models.ImageField(blank=True, default='', upload_to='uploads/')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phonenumber', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, default='', null=True)),
                ('next_of_kin', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('next_of_kin_phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('country_of_orgin', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('amount_paid_so_far', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, max_length=255, null=True)),
                ('amount_to_pay', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=15, max_length=255, null=True)),
                ('brought_by', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('currency_of_choice', models.CharField(choices=[('USD', '$'), ('Ugandan Shillings', 'UGX'), ('Naira', '₦'), ('Euro', '€')], default='US', max_length=100)),
                ('country_of_destination', models.CharField(blank=True, choices=[('Australia', 'Australia'), ('Canada', 'Canada'), ('USA', 'USA'), ('Shengen', 'Shengen'), ('Israel', 'Israel')], default='US', max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('has_done_biometry_before', models.BooleanField(default=False)),
                ('biometry_date', models.DateField(blank=True, default='', null=True)),
                ('has_done_biometry', models.BooleanField(default=False)),
                ('has_obtained_visa_before', models.BooleanField(default=False)),
                ('has_obtained_visa', models.BooleanField(default=False)),
                ('rejected', models.CharField(choices=[('0', '0'), ('once', '1'), ('twice', '2'), ('thrice', '3'), ('fourth', '4'), ('fith', '5')], default='', max_length=15, null=True)),
                ('Departure_date', models.DateField(blank=True, default='', null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_paid', models.BooleanField(default=False)),
                ('amount_paid', models.CharField(default='', max_length=100)),
                ('paid_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now=True, null=True)),
                ('evidence_document', models.ImageField(blank=True, default='', upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
