# Generated by Django 3.2.15 on 2022-09-30 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount_paid_so_far',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='amount_paid_today',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='brought_by',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_of_destination',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('Canada', 'Canada'), ('USA', 'USA'), ('Shengen', 'Shengen'), ('Israel', 'Israel')], default='US', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_of_orgin',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_passport',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
