# Generated by Django 3.2.15 on 2022-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currency_of_choice',
            field=models.CharField(blank=True, choices=[('USD', '$'), ('Ugandan Shillings', 'UGX'), ('Naira', '₦'), ('Euro', '€')], default='US', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=15, null=True),
        ),
    ]
