# Generated by Django 3.2.15 on 2022-09-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220930_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount_paid_so_far',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='amount_paid_today',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='none@email.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='next_of_kin',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
