# Generated by Django 3.2.15 on 2022-11-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
