# Generated by Django 3.2.15 on 2022-11-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_done_biometry_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
