# Generated by Django 3.2.15 on 2022-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221128_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brought_by',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
