# Generated by Django 3.2.15 on 2022-11-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_brought_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rejected',
            field=models.CharField(choices=[('0', '0'), ('once', '1'), ('twice', '2'), ('thrice', '3'), ('fourth', '4'), ('fith', '5')], default='', max_length=15, null=True),
        ),
    ]
