# Generated by Django 3.2.15 on 2022-11-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221128_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='covid_certificate',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_document',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='user',
            name='yellow_fever',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
