# Generated by Django 3.2.15 on 2022-10-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashmemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashmemo_of', models.CharField(default='i.e: Repair fee', max_length=250)),
                ('cashmemo_by', models.CharField(default='i.e: The name of the person', max_length=250)),
                ('amount', models.IntegerField(default='0')),
                ('day_on_which', models.DateField(blank=True, null=True)),
                ('evidence_document', models.ImageField(blank=True, default='', upload_to='uploads/')),
                ('signature', models.ImageField(blank=True, default='', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_date', models.DateField(blank=True, null=True)),
                ('amount_paid_or_paying', models.CharField(default='', max_length=250)),
                ('status', models.CharField(blank=True, choices=[('in', 'in'), ('out', 'out'), ('pending', 'pending')], default='', max_length=10, null=True)),
                ('reason', models.CharField(default='', max_length=250)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
