# Generated by Django 3.2.15 on 2022-10-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_date', models.DateField(blank=True, null=True)),
                ('amount_paid_or_paying', models.CharField(default='', max_length=250)),
                ('status', models.CharField(blank=True, choices=[('in', 'in'), ('out', 'out')], default='', max_length=10, null=True)),
                ('reason', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
