# Generated by Django 3.2.15 on 2022-10-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmemo',
            name='cashmemo_of',
            field=models.CharField(default='i.e: Repair fee', max_length=250, null=True),
        ),
    ]
