# Generated by Django 3.2.15 on 2022-10-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('dashboard', '0002_alter_cashmemo_cashmemo_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(default='i.e: passport', max_length=250, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, default='', upload_to='uploads/')),
                ('document_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
