# Generated by Django 3.2.15 on 2022-11-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_documents_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, max_length=255, null=True),
        ),
    ]
