# Generated by Django 3.2.15 on 2022-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
                ('type_of_visa', models.CharField(choices=[('Working Visa', 'Working Visa'), ('Touring Visa', 'Touring Visa'), ('Studying Visa', 'Studying Visa'), ('Diplomatic Visa', 'Diplomatic Visa'), ('Permanent Residence', 'Permanent Residence')], default='US', max_length=100)),
                ('reason', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
