# Generated by Django 3.2.15 on 2022-09-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220923_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='user',
        ),
    ]
